# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a7cc580428671ac48931967620c0279a02e472ad11e3dcf6871561b6629b16fbd1dd065d85272fe84f6bf155c36da55c735050e9ad24fc746811857c4cd8d0f

test:
  secret_key_base: 2bc3e7085bd39fc7c7da0bffb9191ce4cff711f7503ee96c05cca24b0ece8003e11bbc60725652b3521460260e7e633d81501e40e41563a50440034f41ca22bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
